kind: Deployment
apiVersion: apps/v1
metadata:
  name: nuxt-natricon-deployment
  namespace: natricon
  labels:
    app: nuxt-natricon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuxt-natricon
  template:
    metadata:
      labels:
        app: nuxt-natricon
    spec:
      containers:
      - name: nuxt-natricon
        image: replaceme
        ports:
          - containerPort: 3000
        imagePullPolicy: "Always"
      imagePullSecrets:
          - name: regcred