kind: Service
apiVersion: v1
metadata:
  name: nuxt-natricon-service
  namespace: natricon
spec:
  selector:
      app: nuxt-natricon
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000