kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-natricon-deployment
  namespace: natricon
  labels:
    app: go-natricon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-natricon
  template:
    metadata:
      labels:
        app: go-natricon
    spec:
      containers:
      - name: go-natricon
        image: replaceme
        command: ["/bin/bash", "-c"]
        args: ["natricon -host=0.0.0.0 -port=5555 -logtostderr -rpc-url http://nano-node.nano:7076"]
        ports:
          - containerPort: 5555
        imagePullPolicy: "Always"
        env:
          - name: REDIS_HOST
            value: redis-0.redis
          - name: REDIS_DB
            value: "13"
          - name: NATRICON_SEED
            valueFrom:
              secretKeyRef:
                name: natricon
                key: seed
      imagePullSecrets:
          - name: regcred
 
