kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-natricon-deployment
  namespace: natricon
  labels:
    app: go-natricon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-natricon
  template:
    metadata:
      labels:
        app: go-natricon
    spec:
      containers:
      - name: go-natricon
        image: replaceme
        ports:
          - containerPort: 5555
        imagePullPolicy: "Always"
      imagePullSecrets:
          - name: regcred