kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-natricon-deployment
  namespace: natricon
  labels:
    app: go-natricon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-natricon
  template:
    metadata:
      labels:
        app: go-natricon
    spec:
      containers:
      - name: go-natricon
        image: replaceme
        command: ["/bin/bash", "-c"]
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 1500Mi
        args: ["natricon -host=0.0.0.0 -port=5555 -logtostderr -rpc-url http://pippin-nano.pippin:11338 -nano-ws-url ws://nano-node.nano:7078"]
        ports:
          - containerPort: 5555
        imagePullPolicy: "Always"
        env:
          - name: DONATION_ACCOUNT
            value: nano_3natricon9grnc8caqkht19f1fwpz39r3deeyef66m3d4fch3fau7x5q57cj
          - name: REDIS_HOST
            value: redis-0.redis
          - name: REDIS_DB
            value: "13"
          - name: NATRICON_SEED
            valueFrom:
              secretKeyRef:
                name: natricon
                key: seed
          - name: WALLET_ID
            valueFrom:
              secretKeyRef:
                name: natricon
                key: wallet_id                
      imagePullSecrets:
          - name: regcred
 
