name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.2'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Run Tests
      run: |
        cd server
        go test ./...

  build_and_publish_nuxt:
    name: Build and Publish Nuxt Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master   
      - name: Build & Publish Nuxt Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 'nuxt-natricon:${{ env.GITHUB_REF }}-${{ env.GITHUB_RUN_ID }}'
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPO }}
          dockerfile: Dockerfile

  build_and_publish_go:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master   
      - name: Build & Publish GO Image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          name: natricon/natricon-server
          tag: ${{ env.GITHUB_REF }}-${{ env.GITHUB_RUN_ID }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPO }}
          dockerfile: Dockerfile
