name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.2'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Run Tests
      run: |
        cd server
        go test ./...

  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master   

      - name: Build & Publish Nuxt Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nuxt-natricon
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPO }}
          dockerfile: Dockerfile
          tags: "${{ env.GITHUB_RUN_ID }}"

      - name: Build & Publish GO Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: go-natricon
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPO }}
          dockerfile: Dockerfile
          tags: "${{ env.GITHUB_RUN_ID }}"
