name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.2'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Run Tests
      run: |
        cd server
        go test ./...

  build_and_publish_nuxt:
    name: Build and Publish Nuxt Image
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}    
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@master   
      - name: Login to registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REPO }}

      - name: Build and tag
        if: success()
        run: docker build -t ${{ secrets.DOCKER_REPO }}/nuxt-natricon:${BRANCH_NAME}-${{ env.GITHUB_RUN_ID }} .

      - name: Push image   
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_REPO }}/nuxt-natricon:${BRANCH_NAME}-${{ env.GITHUB_RUN_ID }}


  build_and_publish_go:
    name: Build and Publish GO Image
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}    
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@master   
      - name: Login to registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REPO }}

      - name: Build and tag
        if: success()
        run: docker build -t ${{ secrets.DOCKER_REPO }}/go-natricon:${BRANCH_NAME}-${{ env.GITHUB_RUN_ID }} server

      - name: Push image   
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_REPO }}/go-natricon:${BRANCH_NAME}-${{ env.GITHUB_RUN_ID }}